# Generated by Django 3.2.6 on 2021-09-26 16:28

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210926_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='countries',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
