# Generated by Django 3.2.6 on 2021-09-26 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_billingadress_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAdress',
            new_name='BillingAddress',
        ),
    ]
